set_property PACKAGE_PIN N14    [get_ports clk]
set_property PACKAGE_PIN J3     [get_ports btn_start]
set_property PACKAGE_PIN L3     [get_ports ENABLE]
set_property PACKAGE_PIN G5     [get_ports SCL]
set_property PACKAGE_PIN G4     [get_ports SDA]
set_property PACKAGE_PIN B7     [get_ports port_state_acknowledge]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports btn_start]
set_property IOSTANDARD LVCMOS33 [get_ports ENABLE]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property IOSTANDARD LVCMOS33 [get_ports port_state_acknowledge]

##set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
##set_property SEVERITY {Warning} [get_drc_checks UCIO-1]