set_property PACKAGE_PIN N14    [get_ports clk]
set_property PACKAGE_PIN L3     [get_ports ENABLE]
set_property PACKAGE_PIN G5     [get_ports SCL]
set_property PACKAGE_PIN G4     [get_ports SDA]
set_property PACKAGE_PIN L4     [get_ports LEDs{2}]
set_property PACKAGE_PIN M4     [get_ports LEDs{1}]
set_property PACKAGE_PIN N3     [get_ports LEDs{0}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports ENABLE]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property IOSTANDARD LVCMOS33 [get_ports LEDs{2}]
set_property IOSTANDARD LVCMOS33 [get_ports LEDs{1}]
set_property IOSTANDARD LVCMOS33 [get_ports LEDs{0}]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]