set_property PACKAGE_PIN N14 [get_ports clk_in]
set_property PACKAGE_PIN G5 [get_ports scl]
set_property PACKAGE_PIN G4 [get_ports sda]
set_property PACKAGE_PIN L3 [get_ports power_enable]
#set_property PACKAGE_PIN M1 [get_ports ready]
#set_property PACKAGE_PIN M2 [get_ports model_err]
#set_property PACKAGE_PIN N1 [get_ports nack_err]
set_property PACKAGE_PIN M1 [get_ports id_camera{0}]
set_property PACKAGE_PIN M2 [get_ports id_camera{1}]
set_property PACKAGE_PIN N1 [get_ports id_camera{2}]
set_property PACKAGE_PIN P1 [get_ports id_camera{3}]
set_property PACKAGE_PIN R1 [get_ports id_camera{4}]
set_property PACKAGE_PIN R2 [get_ports id_camera{5}]
set_property PACKAGE_PIN T2 [get_ports id_camera{6}]
set_property PACKAGE_PIN R3 [get_ports id_camera{7}]


set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports power_enable]
#set_property IOSTANDARD LVCMOS33 [get_ports ready]
#set_property IOSTANDARD LVCMOS33 [get_ports model_err]
#set_property IOSTANDARD LVCMOS33 [get_ports nack_err]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{0}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{1}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{2}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{3}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{4}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{5}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{6}]
set_property IOSTANDARD LVCMOS33 [get_ports id_camera{7}]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

create_clock -period 20.000 -name clk_in [get_ports clk_in]