# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy.xci
# IP: The module: 'mipi_dphy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_dphy'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_dphy'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_dphy'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy.xci
# IP: The module: 'mipi_dphy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_dphy'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_dphy'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Library_Projects_FPGA/GeopticCam/GeopticCam.srcs/sources_1/ip/mipi_dphy/mipi_dphy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_dphy'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
