webtalk_init -webtalk_dir D:/Library_Projects_FPGA/GeopticCam/GeopticCam.sim/sim_1/behav/xsim/xsim.dir/imx219_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep  9 15:50:10 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9cdf34b-6df0-464e-8c6f-3c23306a7da4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3cafc0222328491db29ca61e1ef64d4e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.76_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6116_KB" -context "xsim\\usage"
webtalk_transmit -clientid 39519419 -regid "" -xml D:/Library_Projects_FPGA/GeopticCam/GeopticCam.sim/sim_1/behav/xsim/xsim.dir/imx219_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Library_Projects_FPGA/GeopticCam/GeopticCam.sim/sim_1/behav/xsim/xsim.dir/imx219_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Library_Projects_FPGA/GeopticCam/GeopticCam.sim/sim_1/behav/xsim/xsim.dir/imx219_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
